dbtest:
  build: ./postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_PASSWORD=password

redistest:
  image: redis
  ports:
    - 6379:6379
  command: redis-server --requirepass password
